use agentguard_core::{init_store, PolicyStore};
use anyhow::{anyhow, Result};
use std::path::Path;

/// Validate an organization name for safe interpolation into a
/// Cedar string literal. Cedar is permissive about identifier chars
/// but a name containing `"`, `\`, or newlines would let a CLI
/// caller inject policy text. We allow ASCII letters/digits/hyphen/
/// underscore/dot, plus spaces. Everything else is rejected.
fn sanitize_org_name(name: &str) -> Result<&str> {
    if name.is_empty() {
        return Err(anyhow!("--name cannot be empty"));
    }
    if name.len() > 64 {
        return Err(anyhow!("--name is too long (max 64 chars)"));
    }
    for c in name.chars() {
        let ok = c.is_ascii_alphanumeric()
            || matches!(c, '-' | '_' | '.' | ' ')
            || c.is_ascii_punctuation() && c != '"' && c != '\\';
        if !ok {
            return Err(anyhow!(
                "--name contains an unsafe character {:?}; allowed: ASCII alphanumeric, '-', '_', '.', ' ', and basic punctuation except quotes and backslashes",
                c
            ));
        }
    }
    Ok(name)
}

pub fn run(store: impl AsRef<Path>, name: &str) -> Result<()> {
    let path = store.as_ref();
    let name = sanitize_org_name(name)?;
    init_store(path)?;
    let store = PolicyStore::open(path)?;

    // The auto-generated `10_admin` policy grants the `User::"admin"`
    // principal ANY action on ANY resource — effectively a global
    // superuser. This is the documented default; operators MUST
    // replace it before any non-development deployment.
    eprintln!(
        "warning: `10_admin.cedar` grants `User::\"admin\"` superuser privileges. \
         Replace this file before deploying to production."
    );
    store.write_policy(
        "10_admin",
        &format!(
            r#"// Auto-generated by `agentguard init` for org `{name}`.
// SECURITY: This policy grants the `User::"admin"` principal ANY
// action on ANY resource. It is a development default only;
// replace this file before deploying to production.
permit (
  principal in User::"admin",
  action,
  resource
);
"#
        ),
    )?;

    // Agents can call any ToolCall action.
    eprintln!(
        "warning: `20_agents.cedar` permits any `Agent` to invoke any declared \
         ToolCall action. Tighten with `when {{ ... }}` clauses before deploying."
    );
    store.write_policy(
        "20_agents",
        r#"// AI agents can invoke any declared ToolCall action.
// SECURITY: This is a development default that grants every agent
// unrestricted tool access. Tighten with `when { ... }` clauses
// before deploying.
permit (
  principal is Agent,
  action,
  resource
);
"#,
    )?;

    println!("Initialized agentguard store at {}", store.root.display());
    println!("  schema: {}", store.schema_path().display());
    println!("  policies: {}", store.policies_dir().display());
    println!("Try:");
    println!("  agentguard validate");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_allows_safe_names() {
        assert!(sanitize_org_name("acme-corp").is_ok());
        assert!(sanitize_org_name("Acme Corp.").is_ok());
        assert!(sanitize_org_name("acme_corp.io").is_ok());
    }

    #[test]
    fn sanitize_rejects_unsafe() {
        assert!(sanitize_org_name("").is_err());
        assert!(sanitize_org_name(&"x".repeat(65)).is_err());
        assert!(sanitize_org_name(r#"acme"; permit (any); "#).is_err());
        assert!(sanitize_org_name("acme\\inject").is_err());
    }
}
