use agentguard_core::{init_store, PolicyStore};
use anyhow::Result;
use std::path::Path;

pub fn run(store: &str, name: &str) -> Result<()> {
    let path = Path::new(store);
    init_store(path)?;
    let store = PolicyStore::open(path)?;

    // Admins can do anything.
    store.write_policy(
        "10_admin",
        &format!(
            r#"// Auto-generated by `agentguard init` for org `{name}`.
// Admins can do anything to anything.
permit (
  principal in User::"admin",
  action,
  resource
);
"#
        ),
    )?;

    // Agents can call any ToolCall action.
    store.write_policy(
        "20_agents",
        r#"// AI agents can invoke any declared ToolCall action.
// Tighten with `when { ... }` clauses as you learn your needs.
permit (
  principal is Agent,
  action,
  resource
);
"#,
    )?;

    println!("Initialized agentguard store at {}", store.root.display());
    println!("  schema: {}", store.schema_path().display());
    println!("  policies: {}", store.policies_dir().display());
    println!("Try:");
    println!("  agentguard validate");
    Ok(())
}
